name:                day2
version:             0.1.0.0
github:              "angolon/day2"
license:             BSD3
author:              "Angus Gerry"
maintainer:          "angolon@gmail.com"
copyright:           "2021 Angus Gerry"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/angolon/day2#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1.14.0 && < 4
- free >= 5.1.7 && < 6
- lens >= 4.19.2
- containers >= 0.6.5.1 && < 1
- monoidal-containers >= 0.6.1 && < 1
- assoc >= 1.0.2 && < 2
- vector >= 0.12.3.1 && < 1 

library:
  source-dirs: src

executables:
  day2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day2

tests:
  day2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day2
